version: '2'
services:
  traefik:
    image: traefik:v1.3.2
    container_name: traefik
    restart: unless-stopped
    command: --consul --consul.endpoint=consul:8500
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./certs:/etc/traefik/ssl"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/etc/traefik/conf/traefik.toml"
    logging:
      options:
        max-size: 50m
  
  dnsmasq:
    image: lagardere/dnsmasq
    container_name: dnsmasq
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:8080"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    logging:
      options:
        max-size: 50m
  consul:
    image: consul
    container_name: consul
    volumes:
      - "./certs:/etc/traefik/ssl"
    ports:
      - "8500:8500"
networks:
  default:
    external:
      name: traefik