FROM alpine:3.6

RUN apk -U add curl bash openssl \
  	&& curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.05.0-ce.tgz && tar --strip-components=1 -xvzf docker-17.05.0-ce.tgz -C /usr/bin \
  	&& apk del curl \
  	&& rm -rf /var/cache/apk/*

CMD /scripts/ssl/watcher