version: '2'

services:
  traefik:
    image: traefik:v1.3.3
    container_name: traefik
    restart: unless-stopped
    command: --consul --consul.endpoint=consul:8500
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging:
      options:
        max-size: 1m
  
  dnsmasq:
    build:
      context: .
      dockerfile: Dockerfile-dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/udp"
      - "8053:8080"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    logging:
      options:
        max-size: 1m
  consul:
    image: consul
    container_name: consul
    restart: unless-stopped
    hostname: consul
    command: agent -server -client 0.0.0.0 -data-dir=/consul/data -config-dir=/consul/config -ui -bootstrap-expect 1
    volumes:
      - "./data:/data:ro"
      - "./scripts/kvstore/kvstore:/usr/bin/kvstore:ro"
    ports:
      - "8500:8500"
    logging:
      options:
        max-size: 1m

  watcher:
    build:
      context: .
      dockerfile: Dockerfile-watcher
    container_name: watcher
    restart: unless-stopped
    environment:
      - ROOT_CA_PASSWORD=secret
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./scripts:/scripts:ro"
      - "./data:/data"
    logging:
      options:
        max-size: 1m
networks:
  default:
    external:
      name: traefik