version: '2'

services:
  traefik:
    image: traefik:v1.3.3
    container_name: traefik
    restart: unless-stopped
    command: --consul --consul.endpoint=consul:8500
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging:
      options:
        max-size: 50m
  
  dnsmasq:
    build:
      context: .
      dockerfile: Dockerfile-dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:8080"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    logging:
      options:
        max-size: 50m
  
  consul:
    image: consul
    container_name: consul
    volumes:
      - "./data:/data:ro"
      - "./scripts/kvstore/kvstore:/usr/bin/kvstore:ro"
    ports:
      - "8500:8500"

networks:
  default:
    external:
      name: traefik