version: '2'
services:
  traefik:
    image: traefik:v1.3.2
    container_name: traefik
    restart: always
    command:
      - --defaultEntryPoints=https,http
      - --docker
      - --docker.exposedbydefault=false
      - --logLevel=INFO
      - --web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    logging:
      options:
        max-size: 50m
  dnsmasq:
    image: lagardere/dnsmasq
    container_name: dnsmasq
    restart: always
    ports:
      - "53:53/udp"
      - "8053:8080"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    logging:
      options:
        max-size: 50m
networks:
  default:
    external:
      name: traefik