#!/bin/bash

network_initialize() {
    _not_implemented_warn
}

network_before_enable() {
    _not_implemented_warn
}

network_enable() {
    local SECONDARY_DNS=$(network_local_dns)
    netsh interface ipv4 add dnsserver "Ethernet" 127.0.0.1 index=1
    netsh interface ipv4 add dnsserver "Ethernet" $SECONDARY_DNS index=2
}

network_disable() {
    netsh interface ip set dns "Ethernet" dhcp
}

network_local_ip() {
    hostname -I | cut -d' ' -f2 
}

network_local_dns() {
    sleep 10
    nslookup google.com | sed -n 2p | awk '{ print $2 }'
}

network_add_root_ca() {
    _not_implemented_warn
}

_not_implemented_warn() {
    echo "[warn] \"$__cmd\" is not yet implemented on windows"
    echo " ---> please read the windows documentation provided with this project"
}

_not_implemented_error() {
    echo >&2 "[error] \"$__cmd\" is not yet implemented on windows"
    exit 1
}
