# This docker-compose show how to use Traefik on your machine
# It will expose a demo container at dev.demo.europe1.fr
version: '2'
services:
  demo:
    image: "emilevauge/whoami"
    networks:
      - "traefik"
      - "default"
    labels:
      - "ssl.domain=dev.www.google.com"
      - "ssl.domain.alt_names=dev.www.google.com,dev.cdn.cacaprout.com"
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.backend=cacaprout"
      - "traefik.frontend.rule=HostRegexp: {subdomain:[a-z.]+}.google.com"
networks:
  traefik:
    external: true